### ISSUE TITLE
Migration to mc-modpack-kit

### ISSUE THREAD

**Issue by jh-devv** [LifeMC-Studios/LifeMC#256]

**Comment by jh-devv** [comment]
@Nukecraft5419 can this be deleted?

**Comment by Nukecraft5419** [comment]
@jh-devv Excuse me there is between something I wrote about discord it was just an opinion you asked what I thought

**Comment by jh-devv** [comment]
> @jh-devv Excuse me there is between something I wrote about discord it was just an opinion you asked what I thought

yea?
it's kinda of an "hot topic" for me

**Comment by Nukecraft5419** [comment]
You could have said it before I had my thank you I still have it

**Comment by jh-devv** [comment]
> You could have said it before I had my thank you I still have it

???

**Comment by jh-devv** [comment]
I'm deeply sorry, but when you continue this, in the programming space, DO NOT mention your political opinions
I'm not in either side of this topic
I want you to delete this

**Comment by Nukecraft5419** [comment]
perfect i understand i will eliminate this problem
